name: actions
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i -g pnpm
    - run: pnpm install
    - run: pnpm bootstrap
    - run: pnpm test
    - run: pnpm test run --filter ./examples
